Document: seek-bzip2
Title: Debian seek-bzip2 Manual
Author: <insert document author here>
Abstract: This manual describes what seek-bzip2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/seek-bzip2/seek-bzip2.sgml.gz

Format: postscript
Files: /usr/share/doc/seek-bzip2/seek-bzip2.ps.gz

Format: text
Files: /usr/share/doc/seek-bzip2/seek-bzip2.text.gz

Format: HTML
Index: /usr/share/doc/seek-bzip2/html/index.html
Files: /usr/share/doc/seek-bzip2/html/*.html
